// widget/DefaultWidget/components/Alert.vue
<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref, useTemplateRef } from 'vue';
import { useI18n } from 'vue-i18n';
import { ERROR_ALERT } from '../../../sdk/ElixirChatEventTypes';
import { normalizeErrorStack } from '../../../utilsCommon';
import { extractErrorMessage } from '../../../sdk/GraphQLClient';
import { useElixirChatWidget } from '../composables/useElixirChatWidget';
import FormattedMarkdown from './FormattedMarkdown.vue';

type AlertPayload = {
  customMessage?: string;
  error?: any;
  retryCallback?: () => void;
};

const { t } = useI18n();
const elixirChatWidget = useElixirChatWidget();
const messageBlockRef = useTemplateRef<HTMLDivElement>('messageBlockRef');

const isOpen = ref(false);
const isExpanded = ref(false);
const emailText = ref('');
const errorDetails = ref('');
const errorStack = ref('');
const alertData = ref<AlertPayload>({});

function resetErrorBlockHeight() {
  try {
    if (messageBlockRef.value) {
      messageBlockRef.value.style.height = 'auto';
    }
  } catch {}
}

function setErrorBlockHeight() {
  if (!isOpen.value) {
    return;
  }
  requestAnimationFrame(() => {
    try {
      if (messageBlockRef.value) {
        messageBlockRef.value.style.height = `${messageBlockRef.value.offsetHeight}px`;
      }
    } catch {}
  });
}

function generateErrorDetails(payload: AlertPayload) {
  const { customMessage, error } = payload || {};
  const maxErrorDetailsLength = 300;
  const networkFailureKeys = [
    'Failed to fetch',
    'NetworkError when attempting to fetch resource'
  ];

  const networkFailureMessage = t('could_not_reach_server');
  for (let i = 0; i < networkFailureKeys.length; i += 1) {
    if ((error?.message || '').toLowerCase().includes(networkFailureKeys[i].toLowerCase())) {
      return networkFailureMessage;
    }
  }

  const details = customMessage || extractErrorMessage(error) || '';
  const trimmed = details.slice(0, maxErrorDetailsLength);
  return details.length > maxErrorDetailsLength ? `${trimmed}…` : details;
}

function generateEmailText(payload: AlertPayload, details: string, stack: string) {
  const { firstName, lastName, id } = elixirChatWidget.client;

  return t('support_chat_error_info', {
    errorDetails: details,
    firstName,
    lastName,
    id,
    error: payload.customMessage || extractErrorMessage(payload.error),
    timestamp: new Date().toString(),
    userAgent: navigator.userAgent,
    screenWidth: screen.availWidth,
    screenHeight: screen.availHeight,
    devicePixelRatio: window.devicePixelRatio,
    errorStack: stack
  });
}

function generateMailToHref() {
  const subject = t('support_chat_error');
  return `mailto:${elixirChatWidget.widgetSupportEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(emailText.value)}`;
}

function onRetryClick() {
  if (alertData.value.retryCallback) {
    resetErrorBlockHeight();
    isOpen.value = false;
    alertData.value.retryCallback();
  }
}

function onCloseClick() {
  resetErrorBlockHeight();
  isOpen.value = false;
  isExpanded.value = false;
}

function onCollapseClick() {
  isExpanded.value = false;
}

function onExpandToEmailClick() {
  isExpanded.value = true;
}

function onEmailTextInput(event: Event) {
  emailText.value = (event.target as HTMLTextAreaElement).value;
}

function onAlertShow(payload: AlertPayload) {
  if (isOpen.value) {
    return;
  }

  const stack = normalizeErrorStack(new Error().stack, 18);
  const details = generateErrorDetails(payload);
  const mailText = generateEmailText(payload, details, stack);

  isOpen.value = true;
  errorDetails.value = details;
  errorStack.value = stack;
  emailText.value = mailText;
  alertData.value = payload;

  nextTick(() => {
    elixirChatWidget.waitForPopupToOpen(setErrorBlockHeight);
  });
}

onMounted(() => {
  elixirChatWidget.on(ERROR_ALERT, onAlertShow);
});

onBeforeUnmount(() => {
  elixirChatWidget.off(ERROR_ALERT, onAlertShow);
});
</script>

<template>
  <div
    class="elixirchat-alert"
    :class="{
      'elixirchat-alert--open': isOpen,
      'elixirchat-alert--expanded': isExpanded
    }"
  >
    <span class="elixirchat-alert__background" />
    <div
      ref="messageBlockRef"
      class="elixirchat-alert__block"
    >
      <template v-if="!isExpanded">
        <h3 class="elixirchat-alert__header-title">
          {{ t('error') }}
        </h3>
        <i
          class="elixirchat-alert__header-icon icon-close-thin"
          @click="onCloseClick"
        />
        <formatted-markdown
          class="elixirchat-alert__message"
          :markdown="errorDetails"
        />
        <div class="elixirchat-alert__button-block">
          <button
            class="elixirchat-alert__retry-button"
            @click="onRetryClick"
          >
            {{ t('try_again') }}
          </button>
          <span
            class="elixirchat-alert__expand-link"
            @click="onExpandToEmailClick"
          >
            {{ t('contact_via_email') }}
          </span>
        </div>
      </template>

      <template v-else>
        <h3 class="elixirchat-alert__header-title">
          {{ t('report_a_problem') }}
        </h3>
        <i
          class="elixirchat-alert__header-icon icon-close-thin"
          @click="onCollapseClick"
        />
        <textarea
          class="elixirchat-alert__error-text"
          :value="emailText"
          @input="onEmailTextInput"
        />
        <a
          class="elixirchat-alert__send-email-button"
          :href="generateMailToHref()"
          target="_blank"
        >
          {{ t('send_to_email', { email: elixirChatWidget.widgetSupportEmail }) }}
        </a>
      </template>
    </div>
  </div>
</template>

// widget/DefaultWidget/Alert.tsx
import React, { Component, Fragment } from 'react';
import { FormattedMessage, injectIntl } from 'react-intl';
import { ERROR_ALERT } from '../../sdk/ElixirChatEventTypes';
import { cn, normalizeErrorStack } from '../../utilsCommon';
import { exposeComponentToGlobalScope } from '../../utilsWidget';
import { extractErrorMessage } from '../../sdk/GraphQLClient';
import { FormattedMarkdown } from './FormattedMarkdown';

export interface IDefaultWidgetAlertProps {
  elixirChatWidget: any;
}

export interface IDefaultWidgetAlertState {}

class AlertComponent extends Component<IDefaultWidgetAlertProps, IDefaultWidgetAlertState> {

  state = {
    isOpen: false,
    isExpanded: false,
    emailText: '',
    errorDetails: '',
    errorStack: '',
    alertData: {},
  };

  messageBlock = React.createRef();

  componentDidMount() {
    const { elixirChatWidget } = this.props;
    elixirChatWidget.on(ERROR_ALERT, this.onAlertShow);
    exposeComponentToGlobalScope(this, elixirChatWidget);
  }

  onAlertShow = (alertData) => {
    const { elixirChatWidget } = this.props;
    const { isOpen } = this.state;
    if (isOpen) {
      return;
    }

    const errorStack = normalizeErrorStack(new Error().stack, 18);
    const errorDetails = this.generateErrorDetails(alertData);
    const emailText = this.generateEmailText(alertData, errorDetails, errorStack);
    this.setState({
      isOpen: true,
      errorDetails,
      errorStack,
      emailText,
      alertData,
    }, () => {
      elixirChatWidget.waitForPopupToOpen(this.setErrorBlockHeight);
    });
  };

  setErrorBlockHeight = () => {
    // Needed for CSS height transition to work
    const { isOpen } = this.state;
    if (isOpen) {
      requestAnimationFrame(() => {
        try {
          this.messageBlock.current.style.height = this.messageBlock.current.offsetHeight + 'px';
        }
        catch (e) {}
      });
    }
  };

  resetErrorBlockHeight = () => {
    try {
      this.messageBlock.current.style.height = 'auto';
    }
    catch (e) {}
  };

  generateErrorDetails = (alertData) => {
    const { customMessage, error } = alertData || {};
    const maxErrorDetailsLength = 300;
    const networkFailureKeys = [
      'Failed to fetch',
      'NetworkError when attempting to fetch resource'
    ];

    const networkFailureMessage = this.props.intl.formatMessage({ id: 'could_not_reach_server' });
    for (let i = 0; i < networkFailureKeys.length; i++) {
      if ((error?.message || '').toLowerCase().includes( networkFailureKeys[i].toLowerCase() )) {
        return networkFailureMessage;
      }
    }
    const errorDetails = customMessage || extractErrorMessage(error);
    return errorDetails.slice(0, maxErrorDetailsLength) + errorDetails.length > maxErrorDetailsLength ? '…' : '';
  };

  generateEmailText = (alertData, errorDetails, errorStack) => {
    const { elixirChatWidget } = this.props;
    const { client: { firstName, lastName, id } } = elixirChatWidget;

    return this.props.intl.formatMessage({ id: 'support_chat_error_info' }, {
      errorDetails,
      firstName,
      lastName,
      id,
      error: alertData.customMessage || extractErrorMessage(alertData.error),
      timestamp: new Date().toString(),
      userAgent: navigator.userAgent,
      screenWidth: screen.availWidth,
      screenHeight: screen.availHeight,
      devicePixelRatio: window.devicePixelRatio,
      errorStack
    });
  };

  generateMailToHref = () => {
    const { elixirChatWidget } = this.props;
    const { emailText } = this.state;
    const subject = this.props.intl.formatMessage({ id: 'support_chat_error' });
    return `mailto:${elixirChatWidget.widgetSupportEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(emailText)}`;
  };

  onRetryClick = () => {
    const { alertData } = this.state;
    if (alertData.retryCallback) {
      this.resetErrorBlockHeight();
      this.setState({ isOpen: false });
      alertData.retryCallback();
    }
  };

  onCloseClick = () => {
    this.resetErrorBlockHeight();
    this.setState({
      isOpen: false,
      isExpanded: false,
    });
  };

  onCollapseClick = () => {
    this.setState({ isExpanded: false });
  };

  onExpandToEmailClick = () => {
    this.setState({ isExpanded: true });
  };

  render() {
    const { elixirChatWidget } = this.props;
    const {
      emailText,
      errorDetails,
      isExpanded,
      isOpen,
    } = this.state;

    return (
      <div className={cn({
        'elixirchat-alert': true,
        'elixirchat-alert--open': isOpen,
        'elixirchat-alert--expanded': isExpanded,
      })}>
        <span className="elixirchat-alert__background"/>
        <div className="elixirchat-alert__block" ref={this.messageBlock}>
          {!isExpanded && (
            <Fragment>
              <h3 className="elixirchat-alert__header-title">
                <FormattedMessage id="error" />
              </h3>
              <i className="elixirchat-alert__header-icon icon-close-thin"
                onClick={this.onCloseClick}/>
              <FormattedMarkdown
                className="elixirchat-alert__message"
                markdown={errorDetails}/>
              <div className="elixirchat-alert__button-block">
                <button className="elixirchat-alert__retry-button" onClick={this.onRetryClick}>
                  <FormattedMessage id="try_again" />
                </button>
                <span className="elixirchat-alert__expand-link" onClick={this.onExpandToEmailClick}>
                  <FormattedMessage id="contact_via_email" />
                </span>
              </div>
            </Fragment>
          )}

          {isExpanded && (
            <Fragment>
              <h3 className="elixirchat-alert__header-title">
                <FormattedMessage id="report_a_problem" />
              </h3>
              <i className="elixirchat-alert__header-icon icon-close-thin"
                onClick={this.onCollapseClick}/>
              <textarea className="elixirchat-alert__error-text"
                value={emailText}
                onChange={e => this.setState({ emailText: e.target.value })}/>
              <a className="elixirchat-alert__send-email-button"
                href={this.generateMailToHref()}
                target="_blank">
                <FormattedMessage id="send_to_email" values={{ email: elixirChatWidget.widgetSupportEmail }} />
              </a>
            </Fragment>
          )}
        </div>
      </div>
    );
  }
}

export const Alert = injectIntl(AlertComponent);
