// widget/DefaultWidget/components/ChatTextarea.vue
<script setup lang="ts">
import { ref, useTemplateRef, watch, onMounted, onBeforeUnmount, nextTick } from 'vue';
import { useStorage, useTextareaAutosize } from '@vueuse/core';
import { useI18n } from 'vue-i18n';
import { useElixirChatWidget } from '@defaultWidget/composables/useElixirChatWidget';
import { randomDigitStringId } from '@root/utilsCommon';
import { MESSAGES_HISTORY_CHANGE, TYPING_STATUS_SUBSCRIBE_SUCCESS } from '@sdk/ElixirChatEventTypes';
import {
  WIDGET_REPLY_MESSAGE,
  WIDGET_TEXTAREA_RESIZE,
  WIDGET_FULLSCREEN_PREVIEW_CLOSE,
  WIDGET_SCREENSHOT_REQUEST_SUCCESS,
  WIDGET_SCREENSHOT_REQUEST_ERROR,
  WIDGET_MUTE_TOGGLE,
  WIDGET_POPUP_OPEN,
  WIDGET_IFRAME_READY

} from '@widget/ElixirChatWidgetEventTypes';
import { generateReplyMessageQuote, getImageDimensions } from '@root/utilsWidget';
import ActionsDropdown from './ActionsDropdown.vue';

const TYPED_TEXT_STORAGE_KEY = 'elixirchat-typed-text';

type LocallySavedTypedText = {
  textareaText: string;
  textareaResponseToMessageId: string | null;
};

type Attachment = {
  id: string;
  file: File;
  name: string;
  width: number;
  height: number;
  isScreenshot?: boolean;
};

const { t } = useI18n();

const elixirChatWidget = useElixirChatWidget();

const textareaRef = useTemplateRef<HTMLTextAreaElement>('textareaRef');
const textareaContainerRef = useTemplateRef<HTMLDivElement>('textareaContainer');
const inputFileRef = useTemplateRef<HTMLInputElement>('inputFileRef');

const textareaText = ref('');
const textareaResponseToMessageId = ref<string | null>(null);
const textareaAttachments = ref<Attachment[]>([]);
const responseToMessage = ref<any>(undefined);
const isSubmittingMessage = ref(false);
const isDraggingAttachments = ref(false);
const hasCanceledDraggingAttachments = ref(false);
const screenshotFallback = ref<object | null>(null);
const locallySavedTypedText = useStorage<LocallySavedTypedText>(
  TYPED_TEXT_STORAGE_KEY,
  {
    textareaText: '',
    textareaResponseToMessageId: null
  },
  localStorage,
  { mergeDefaults: true }
);

function focusTextarea() {
  setTimeout(() => {
    textareaRef.value?.focus();
  });
}

function onVerticalResize() {
  requestAnimationFrame(() => {
    const container = textareaContainerRef.value;
    if (container) {
      elixirChatWidget.triggerEvent(WIDGET_TEXTAREA_RESIZE, container.offsetHeight);
    }
  });
}

const { triggerResize } = useTextareaAutosize({
  element: textareaRef,
  input: textareaText,
  onResize: onVerticalResize
});

function onTextareaChange() {
  const text = textareaText.value;
  elixirChatWidget.dispatchTypedText(text);
  updateLocallySavedTypedText({ textareaText: text });
}

function onTextareaKeyDown(e: KeyboardEvent) {
  if (e.key === 'Enter' && e.shiftKey === false) {
    e.preventDefault();

    if (!textareaText.value.trim() && !textareaAttachments.value.length) {
      return;
    }

    onMessageSubmit();
    reset();
  }
}

function handleAttachmentPaste(e: ClipboardEvent) {
  const items = Array.from(e.clipboardData?.items || []);
  const fileItem = items.find((i) => i.kind === 'file');
  if (!fileItem) {
    return;
  }
  const file = fileItem.getAsFile();
  if (!file) {
    return;
  }
  e.preventDefault();
  addAttachments([
    {
      name: t('pasted_from_clipboard'),
      file
    }
  ]);
}

function onWidgetPopupDrag(e: DragEvent) {
  e.preventDefault();
  e.stopPropagation();
  isDraggingAttachments.value = true;
  if (!hasCanceledDraggingAttachments.value) {
    hasCanceledDraggingAttachments.value = true;
    requestAnimationFrame(() => {
      elixirChatWidget.widgetIFrameDocument?.body?.addEventListener('dragleave', onWidgetPopupDragLeave);
    });
  }
}
function onWidgetPopupDragLeave() {
  elixirChatWidget.widgetIFrameDocument?.body?.removeEventListener('dragleave', onWidgetPopupDragLeave);
  isDraggingAttachments.value = false;
  hasCanceledDraggingAttachments.value = false;
}
function cancelWidgetPopupDrag() {
  isDraggingAttachments.value = false;
}
function onBodyDrop(e: DragEvent) {
  e.preventDefault();
  e.stopPropagation();
  const items = Array.from(e.dataTransfer?.items || []);
  const files = items
    .filter((item) => item.kind === 'file')
    .map((item) => item.getAsFile())
    .filter((f): f is File => Boolean(f))
    .map((file) => ({
      name: file.name,
      file
    }));
  addAttachments(files);
  cancelWidgetPopupDrag();
}

function reset() {
  textareaText.value = '';
  textareaResponseToMessageId.value = null;
  textareaAttachments.value = [];

  // nextTick(() => triggerResize());
}

function onSubmitClick() {
  if (!textareaText.value.trim() && !textareaAttachments.value.length) {
    return;
  }
  onMessageSubmit();
  reset();
  focusTextarea();
}

function getLocallySavedTypedText(raw: unknown = locallySavedTypedText.value): LocallySavedTypedText {
  const parsed = (raw && typeof raw === 'object') ? raw as Partial<LocallySavedTypedText> : {};
  return {
    textareaText: typeof parsed.textareaText === 'string' ? parsed.textareaText : '',
    textareaResponseToMessageId:
      typeof parsed.textareaResponseToMessageId === 'string'
        ? parsed.textareaResponseToMessageId
        : null
  };
}

function updateLocallySavedTypedText(diff: Partial<LocallySavedTypedText>): void {
  locallySavedTypedText.value = {
    ...getLocallySavedTypedText(locallySavedTypedText.value),
    ...diff
  };
}

function onTypingStatusSubscribeSuccess() {
  elixirChatWidget.dispatchTypedText(getLocallySavedTypedText(locallySavedTypedText.value).textareaText);
}

function onMessageSubmit() {
  if (textareaText.value.trim() || textareaAttachments.value.length) {
    isSubmittingMessage.value = true;

    elixirChatWidget.sendMessage({
      text: textareaText.value,
      attachments: textareaAttachments.value,
      responseToMessageId: textareaResponseToMessageId.value,
      appendConditionally: true
    })
      .finally(() => {
        isSubmittingMessage.value = false;
      });
    elixirChatWidget.dispatchTypedText(false);
    updateLocallySavedTypedText({
      textareaText: '',
      textareaResponseToMessageId: null
    });
  }
}

function updateResponseToMessage() {
  const id = textareaResponseToMessageId.value;
  if (!id) {
    responseToMessage.value = undefined;
    return;
  }
  responseToMessage.value = elixirChatWidget.messageHistory?.find((message) => message.id === id);
}

watch(textareaResponseToMessageId, updateResponseToMessage, { immediate: true });

function onRemoveReplyTo() {
  textareaResponseToMessageId.value = null;
  updateLocallySavedTypedText({ textareaResponseToMessageId: null });
  onVerticalResize();
  focusTextarea();
}

function onReplyMessage(messageId: string) {
  textareaResponseToMessageId.value = messageId;
  updateLocallySavedTypedText({ textareaResponseToMessageId: messageId });
  onVerticalResize();
  focusTextarea();
}

function onMessageHistoryChange() {
  updateResponseToMessage();
}

function onIframeReady() {
  const body = elixirChatWidget.widgetIFrameDocument?.body;
  if (!body) {
    return;
  }
  body.addEventListener('dragover', onWidgetPopupDrag);
  body.addEventListener('drop', onBodyDrop);
}

function onScreenshotRequestSuccess(screenshot: { file: File }) {
  addAttachments([
    {
      name: t('screenshot'),
      file: screenshot.file,
      isScreenshot: true
    }
  ]);
  elixirChatWidget.openPopup();
  if (!textareaText.value.trim()) {
    textareaText.value = t('here_is_the_screenshot');
  }
}

function onScreenshotRequestError() {
  elixirChatWidget.openPopup();
}

function onScreenShotClick() {
  elixirChatWidget.closePopup();
  elixirChatWidget.takeScreenshot();
}

function onAttachFileClick() {
  inputFileRef.value?.click();
}

async function addAttachments(newAttachments: Array<{
  name: string;
  file: File;
  isScreenshot?: boolean;
}>) {
  const enriched: Attachment[] = [];
  for (const attachment of newAttachments) {
    const id = randomDigitStringId(6);
    const imageBlobUrl = URL.createObjectURL(attachment.file);
    const dimensions = await getImageDimensions(imageBlobUrl);
    enriched.push({
      id,
      file: attachment.file,
      name: attachment.name,
      width: dimensions.width,
      height: dimensions.height,
      isScreenshot: attachment.isScreenshot
    });
  }
  textareaAttachments.value = [...textareaAttachments.value, ...enriched];
  onVerticalResize();
  focusTextarea();
}

function onInputFileChange(e: Event) {
  const target = e.target as HTMLInputElement;
  const files = Array.from(target.files || []);
  const attachments = files.map((file) => ({
    name: file.name,
    file
  }));
  addAttachments(attachments);
  target.value = '';
}

function removeAttachment(attachmentId: string) {
  textareaAttachments.value = textareaAttachments.value.filter((a) => a.id !== attachmentId);
  onVerticalResize();
  focusTextarea();
}

onMounted(() => {
  const saved = getLocallySavedTypedText(locallySavedTypedText.value);
  textareaText.value = saved.textareaText;
  textareaResponseToMessageId.value = saved.textareaResponseToMessageId;

  elixirChatWidget.on(TYPING_STATUS_SUBSCRIBE_SUCCESS, onTypingStatusSubscribeSuccess);
  elixirChatWidget.on(WIDGET_REPLY_MESSAGE, onReplyMessage);
  elixirChatWidget.on(MESSAGES_HISTORY_CHANGE, onMessageHistoryChange);
  elixirChatWidget.on(WIDGET_SCREENSHOT_REQUEST_SUCCESS, onScreenshotRequestSuccess);
  elixirChatWidget.on(WIDGET_SCREENSHOT_REQUEST_ERROR, onScreenshotRequestError);
  elixirChatWidget.on(WIDGET_IFRAME_READY, onIframeReady);
  window.addEventListener('dragover', cancelWidgetPopupDrag);
  elixirChatWidget.on(WIDGET_FULLSCREEN_PREVIEW_CLOSE, focusTextarea);
  elixirChatWidget.on(WIDGET_MUTE_TOGGLE, focusTextarea);
  elixirChatWidget.on(WIDGET_POPUP_OPEN, focusTextarea);
  elixirChatWidget.on(WIDGET_POPUP_OPEN, onVerticalResize);

  nextTick(() => triggerResize());

  setTimeout(() => {
    focusTextarea();
    onVerticalResize();
  });
});

onBeforeUnmount(() => {
  elixirChatWidget.off(TYPING_STATUS_SUBSCRIBE_SUCCESS, onTypingStatusSubscribeSuccess);
  elixirChatWidget.off(WIDGET_REPLY_MESSAGE, onReplyMessage);
  elixirChatWidget.off(MESSAGES_HISTORY_CHANGE, onMessageHistoryChange);
  elixirChatWidget.off(WIDGET_SCREENSHOT_REQUEST_SUCCESS, onScreenshotRequestSuccess);
  elixirChatWidget.off(WIDGET_SCREENSHOT_REQUEST_ERROR, onScreenshotRequestError);
  elixirChatWidget.off(WIDGET_IFRAME_READY, onIframeReady);
  elixirChatWidget.off(WIDGET_FULLSCREEN_PREVIEW_CLOSE, focusTextarea);
  elixirChatWidget.off(WIDGET_MUTE_TOGGLE, focusTextarea);
  elixirChatWidget.off(WIDGET_POPUP_OPEN, focusTextarea);
  elixirChatWidget.off(WIDGET_POPUP_OPEN, onVerticalResize);

  const body = elixirChatWidget.widgetIFrameDocument?.body;
  body?.removeEventListener('dragover', onWidgetPopupDrag);
  body?.removeEventListener('drop', onBodyDrop);
  body?.removeEventListener('dragleave', onWidgetPopupDragLeave);
  window.removeEventListener('dragover', cancelWidgetPopupDrag);
});
</script>

<template>
  <div
    ref="textareaContainer"
    class="elixirchat-chat-textarea"
  >
    <div
      v-if="responseToMessage"
      class="elixirchat-chat-textarea__reply-to"
    >
      <span class="elixirchat-chat-textarea__reply-to-text">
        <i class="elixirchat-chat-textarea__reply-to-icon icon-reply-right" />
        <span>{{ generateReplyMessageQuote(responseToMessage, elixirChatWidget) }}</span>
      </span>
      <span
        class="elixirchat-chat-textarea__reply-to-remove icon-close-thick"
        role="button"
        tabindex="0"
        @click="onRemoveReplyTo"
      />
    </div>

    <input
      ref="inputFileRef"
      class="elixirchat-chat-textarea__actions-attach-input"
      type="file"
      multiple
      @change="onInputFileChange"
    >

    <textarea
      ref="textareaRef"
      v-model="textareaText"
      class="elixirchat-chat-textarea__textarea"
      :placeholder="t('send_a_message')"
      @input="onTextareaChange"
      @keydown="onTextareaKeyDown"
      @paste="handleAttachmentPaste"
    />
    <div class="elixirchat-chat-textarea__actions-row">
      <actions-dropdown
        @take-screenshoot="onScreenShotClick"
        @attach-file="onAttachFileClick"
      />
      <button
        type="button"
        class="elixirchat-chat-textarea__send-btn"
        :disabled="!textareaText.trim() && !textareaAttachments.length"
        @click="onSubmitClick"
      >
        <i class="icon-send" />
      </button>
    </div>
    <ul
      v-if="textareaAttachments.length"
      class="elixirchat-chat-attachment-list"
    >
      <li
        v-for="attachment in textareaAttachments"
        :key="attachment.id"
        class="elixirchat-chat-attachment-item"
      >
        <i
          class="elixirchat-chat-attachment-icon"
          :class="[attachment.isScreenshot ? 'icon-screenshot' : 'icon-file']"
        />
        <span class="elixirchat-chat-attachment-filename">{{ attachment.name }}</span>
        <i
          class="elixirchat-chat-attachment-remove icon-close-thick"
          tabindex="0"
          @click="removeAttachment(attachment.id)"
        />
      </li>
    </ul>

    <template v-if="isDraggingAttachments">
      <div class="elixirchat-chat-draggable-backdrop" />
      <div class="elixirchat-chat-draggable-area">
        <i class="elixirchat-chat-draggable-area__icon icon-file" />
        <div>{{ t('drop_files') }}</div>
      </div>
    </template>
  </div>
</template>

// widget/DefaultWidget/ChatTextarea.tsx
import React, { Component, Fragment } from 'react';
import { FormattedMessage, injectIntl } from 'react-intl';
import TextareaAutosize from 'react-textarea-autosize';
import { ElixirChatWidget } from '../ElixirChatWidget';
import { Tooltip } from './Tooltip';
import { ActionsDropdown } from './ActionsDropdown';
import { cn, randomDigitStringId, setToLocalStorage } from '../../utilsCommon';
import { getImageDimensions, generateReplyMessageQuote } from '../../utilsWidget';
import { getScreenshotCompatibilityFallback } from '../../sdk/ScreenshotTaker';
import { TYPING_STATUS_SUBSCRIBE_SUCCESS } from '../../sdk/ElixirChatEventTypes';
import {
  WIDGET_REPLY_MESSAGE,
  WIDGET_TEXTAREA_RESIZE,
  WIDGET_FULLSCREEN_PREVIEW_CLOSE,
  WIDGET_SCREENSHOT_REQUEST_SUCCESS,
  WIDGET_SCREENSHOT_REQUEST_ERROR,
  WIDGET_MUTE_TOGGLE,
  WIDGET_POPUP_OPEN,
  WIDGET_IFRAME_READY,
} from '../ElixirChatWidgetEventTypes';

export interface IDefaultWidgetTextareaProps {
  elixirChatWidget: ElixirChatWidget;
  textAreaActiveState: boolean;
}

export interface IDefaultWidgetTextareaState {
  textareaText: string,
  textareaResponseToMessageId: string | null,
  textareaAttachments: Array<{
    id: string;
    file: File;
    name: string;
    width: number;
    height: number;
    isScreenshot?: boolean;
  }>,
  isSubmittingMessage: boolean;
  isDraggingAttachments: boolean;
  hasCanceledDraggingAttachments: boolean;
  screenshotFallback: null | object;
}

class ChatTextareaComponent extends Component<IDefaultWidgetTextareaProps, IDefaultWidgetTextareaState> {

  container = React.createRef();
  inputFile = React.createRef();
  textarea: HTMLTextAreaElement = null;

  state = {
    textareaText: '',
    textareaAttachments: [],
    textareaResponseToMessageId: null,
    isSubmittingMessage: false,
    isDraggingAttachments: false,
    hasCanceledDraggingAttachments: false,
    screenshotFallback: null,
  };

  componentDidMount(): void {
    const { elixirChatWidget } = this.props;

    const savedTypedText = this.getLocallySavedTypedText();
    this.setState(savedTypedText);

    elixirChatWidget.on(TYPING_STATUS_SUBSCRIBE_SUCCESS, () => {
      elixirChatWidget.dispatchTypedText(savedTypedText.textareaText);
    });

    elixirChatWidget.on(WIDGET_SCREENSHOT_REQUEST_SUCCESS, this.onScreenshotRequestSuccess);
    elixirChatWidget.on(WIDGET_SCREENSHOT_REQUEST_ERROR, elixirChatWidget.openPopup);

    elixirChatWidget.on(WIDGET_FULLSCREEN_PREVIEW_CLOSE, this.focusTextarea);
    elixirChatWidget.on(WIDGET_MUTE_TOGGLE, this.focusTextarea);
    elixirChatWidget.on(WIDGET_POPUP_OPEN, this.focusTextarea);
    elixirChatWidget.on(WIDGET_POPUP_OPEN, this.onVerticalResize);

    elixirChatWidget.on(WIDGET_REPLY_MESSAGE, messageId => {
      this.setState({ textareaResponseToMessageId: messageId });
      this.updateLocallySavedTypedText({ textareaResponseToMessageId: messageId });
      this.onVerticalResize();
      this.focusTextarea();
    });

    this.focusTextarea();
    this.setState({ screenshotFallback: getScreenshotCompatibilityFallback() });

    elixirChatWidget.on(WIDGET_IFRAME_READY, () => {
      elixirChatWidget.widgetIFrameDocument.body.addEventListener('dragover', this.onWidgetPopupDrag);
      elixirChatWidget.widgetIFrameDocument.body.addEventListener('drop', this.onBodyDrop);
    });

    window.addEventListener('dragover', this.cancelWidgetPopupDrag);
    window.addEventListener('beforeunload', this.preventLoosingUploadingFiles);
  }

  componentDidUpdate(prevProps: Readonly<IDefaultWidgetTextareaProps>) {
    const { textAreaActiveState } = this.props;

    if (textAreaActiveState && !prevProps.textAreaActiveState) {
      this.focusTextarea();
    }
  }

  componentWillUnmount(){
    const { elixirChatWidget } = this.props;
    elixirChatWidget.widgetIFrameDocument.body.removeEventListener('dragover', this.onWidgetPopupDrag);
    elixirChatWidget.widgetIFrameDocument.body.removeEventListener('drop', this.onBodyDrop);
    window.removeEventListener('dragover', this.cancelWidgetPopupDrag);

    elixirChatWidget.off(WIDGET_MUTE_TOGGLE, this.focusTextarea);
    elixirChatWidget.off(WIDGET_POPUP_OPEN, this.focusTextarea);
    elixirChatWidget.off(WIDGET_POPUP_OPEN, this.onVerticalResize);
  }

  onAttachFileClick = () => {
    this.inputFile.current?.click();
  };

  preventLoosingUploadingFiles = (e) => {
    const { isSubmittingMessage } = this.state;
    if (isSubmittingMessage) {
      e.preventDefault();
      e.returnValue = '';
    }
  };

  onWidgetPopupDrag = (e) => {
    const { hasCanceledDraggingAttachments } = this.state;
    e.preventDefault();
    e.stopPropagation();

    this.setState({ isDraggingAttachments: true });

    if (!hasCanceledDraggingAttachments) {
      this.setState({ hasCanceledDraggingAttachments: true });
      requestAnimationFrame(() => {
        elixirChatWidget.widgetIFrameDocument.body.addEventListener('dragleave', this.onWidgetPopupDragLeave);
      });
    }
  };

  onWidgetPopupDragLeave = () => {
    elixirChatWidget.widgetIFrameDocument.body.removeEventListener('dragleave', this.onWidgetPopupDragLeave);
    this.setState({
      isDraggingAttachments: false,
      hasCanceledDraggingAttachments: false,
    });
  };

  cancelWidgetPopupDrag = () => {
    this.setState({ isDraggingAttachments: false });
  };

  onBodyDrop = (e) => {
    e.preventDefault();
    e.stopPropagation();

    const attachments = Array.from(e.dataTransfer.items || e.dataTransfer.files)
      .filter(item => item.kind === 'file')
      .map(item => {
        const file = item.getAsFile();
        return {
          name: file.name,
          file,
        }
      });

    this.addAttachments(attachments);
    this.cancelWidgetPopupDrag();
  };

  focusTextarea = () => {
    setTimeout(() => {
      this.textarea.focus();
    });
  };

  onVerticalResize = () => {
    const { elixirChatWidget } = this.props;
    requestAnimationFrame(() => {
      const containerElement = this.container.current;
      if (containerElement) {
        elixirChatWidget.triggerEvent(WIDGET_TEXTAREA_RESIZE, containerElement.offsetHeight);
      }
    });
  };

  onTextareaChange = (e): void => {
    const { elixirChatWidget } = this.props;
    const textareaText = e.target.value;
    elixirChatWidget.dispatchTypedText(textareaText);
    this.updateLocallySavedTypedText({ textareaText });
    this.setState({ textareaText });
  };

  getLocallySavedTypedText = () => {
    let currentState = { textareaText: '', textareaResponseToMessageId: null };
    try {
      const { textareaText = '', textareaResponseToMessageId = null } = JSON.parse(
        localStorage.getItem('elixirchat-typed-text')
      );
      currentState = { textareaText, textareaResponseToMessageId };
    }
    catch (e) {}
    return currentState;
  };

  updateLocallySavedTypedText = (diff) => {
    const updatedState = {
      ...this.getLocallySavedTypedText(),
      ...diff
    };
    setToLocalStorage('elixirchat-typed-text', updatedState);
  };

  onTextareaKeyDown = (e) => {
    const {
      textareaText,
      textareaAttachments,
      textareaResponseToMessageId,
    } = this.state;

    if(e.key === 'Enter' && e.shiftKey === false) { // Press "Enter" without holding Shift
      e.preventDefault();
      if (textareaText.trim() || textareaAttachments.length) {
        this.onMessageSubmit({ textareaText, textareaResponseToMessageId, textareaAttachments });
        this.setState({
          textareaText: '',
          textareaResponseToMessageId: null,
          textareaAttachments: [],
        });
        this.onVerticalResize();
      }
    }
  };

  onRemoveReplyTo = () => {
    this.setState({ textareaResponseToMessageId: null });
    this.updateLocallySavedTypedText({ textareaResponseToMessageId: null });
    this.onVerticalResize();
    this.focusTextarea();
  };

  addAttachments = async newAttachments => {
    const { textareaAttachments } = this.state;
    const enrichedNewAttachments = [];

    for (let i = 0; i < newAttachments.length; i++) {
      const attachment = newAttachments[i];
      const id = randomDigitStringId(6);
      const imageBlobUrl = URL.createObjectURL(attachment.file);
      const dimensions = await getImageDimensions(imageBlobUrl);
      enrichedNewAttachments.push({
        id,
        file: attachment.file,
        name: attachment.name,
        width: dimensions.width,
        height: dimensions.height,
        isScreenshot: attachment.isScreenshot,
      });
    }
    this.setState({
      textareaAttachments: [
        ...textareaAttachments,
        ...enrichedNewAttachments,
      ]
    }, () => {
      this.onVerticalResize();
      this.focusTextarea();
    });
  };

  removeAttachment = attachmentId => {
    const { textareaAttachments } = this.state;
    this.setState({
      textareaAttachments: textareaAttachments.filter(item => item.id !== attachmentId)
    });
    this.onVerticalResize();
    this.focusTextarea();
  };

  handleAttachmentPaste = e => {
    const clipboardItem = (e.clipboardData || e.originalEvent.clipboardData || window.clipboardData).items[0];
    if (clipboardItem.kind === 'file') {
      e.preventDefault();
      const file = clipboardItem.getAsFile();
      if (file) {
        this.addAttachments([{
          name: this.props.intl.formatMessage({ id: 'pasted_from_clipboard' }),
          file,
        }]);
      }
    }
  };

  onScreenShotClick = () => {
    const { elixirChatWidget } = this.props;
    elixirChatWidget.closePopup();
    elixirChatWidget.takeScreenshot();
  };

  onScreenshotRequestSuccess = (screenshot) => {
    const { elixirChatWidget } = this.props;
    const { textareaText } = this.state;

    this.addAttachments([{
      name: this.props.intl.formatMessage({ id: 'screenshot' }),
      file: screenshot.file,
      isScreenshot: true,
    }]);

    elixirChatWidget.openPopup();
    const updatedText = textareaText.trim()
      ? textareaText
      : this.props.intl.formatMessage({ id: 'here_is_the_screenshot' });
    this.setState({ textareaText: updatedText });
  };

  onInputFileChange = (e) => {
    const attachments = Array.from(e.target.files).map(file => {
      return {
        name: file.name,
        file: file,
      };
    });
    this.addAttachments(attachments);
    this.inputFile.current.value = '';
  };

  onSubmitClick = () => {
    const { textareaText, textareaAttachments, textareaResponseToMessageId } = this.state;
    if (textareaText.trim() || textareaAttachments.length) {
      this.onMessageSubmit();
      this.setState({
        textareaText: '',
        textareaResponseToMessageId: null,
        textareaAttachments: [],
      });
      this.onVerticalResize();
      this.focusTextarea();
    }
  };

  onMessageSubmit = () => {
    const { elixirChatWidget } = this.props;
    const { textareaText, textareaResponseToMessageId, textareaAttachments } = this.state;

    if (textareaText.trim() || textareaAttachments.length) {
      this.setState({ isSubmittingMessage: true });

      elixirChatWidget
        .sendMessage({
          text: textareaText,
          attachments: textareaAttachments,
          responseToMessageId: textareaResponseToMessageId,
          appendConditionally: true,
        })
        .finally(() => {
          this.setState({ isSubmittingMessage: false });
        });
      elixirChatWidget.dispatchTypedText(false);
      this.updateLocallySavedTypedText({
        textareaText: '',
        textareaResponseToMessageId: null,
      });
    }
  };

  render() {
    const { elixirChatWidget } = this.props;
    const {
      textareaText,
      textareaAttachments,
      textareaResponseToMessageId,
      screenshotFallback,
      isDraggingAttachments,
    } = this.state;

    const responseToMessage = elixirChatWidget.messageHistory.filter(message => {
      return message.id === textareaResponseToMessageId;
    })[0];

    return (
      <Fragment>
        <div className="elixirchat-chat-textarea" ref={this.container}>

          {Boolean(responseToMessage) && (
            <div className="elixirchat-chat-textarea__reply-to">
              <span className="elixirchat-chat-textarea__reply-to-text">
                <i className="elixirchat-chat-textarea__reply-to-icon icon-reply-right"/>
                <span>
                  {generateReplyMessageQuote(responseToMessage, elixirChatWidget)}
                </span>
              </span>
              <span className="elixirchat-chat-textarea__reply-to-remove icon-close-thick"
                onClick={this.onRemoveReplyTo}/>
            </div>
          )}
          <div className="elixirchat-chat-textarea__actions-row">
            <ActionsDropdown
              onAttachFile={this.onAttachFileClick}
              onScreenshot={this.onScreenShotClick}
              screenshotAvailable={!Boolean(screenshotFallback)}
              screenshotLabel={this.props.intl.formatMessage({ id: 'take_a_screenshot' })}
              attachFileLabel={this.props.intl.formatMessage({ id: 'attach_files' })}
            />
            <button
              type="button"
              className="elixirchat-chat-textarea__send-btn"
              onClick={this.onSubmitClick}
              disabled={!textareaText.trim() && !textareaAttachments.length}
            >
              <i className="icon-send" />
            </button>
          </div>
          <input
            className="elixirchat-chat-textarea__actions-attach-input"
            id="DefaultWidget-file-upload"
            type="file"
            ref={this.inputFile}
            multiple={true}
            onChange={this.onInputFileChange}/>

          <TextareaAutosize
            className="elixirchat-chat-textarea__textarea"
            placeholder={this.props.intl.formatMessage({ id: 'send_a_message' })}
            inputRef={tag => {this.textarea = tag;}}
            minRows={1}
            maxRows={5}
            onHeightChange={this.onVerticalResize}
            onPaste={this.handleAttachmentPaste}
            onChange={this.onTextareaChange}
            onKeyDown={this.onTextareaKeyDown}
            value={textareaText}>
          </TextareaAutosize>

          {Boolean(textareaAttachments.length) && (
            <ul className="elixirchat-chat-attachment-list">
              {textareaAttachments.map(attachment => (
                <li key={attachment.id} className="elixirchat-chat-attachment-item">
                  <i className={cn({
                    'elixirchat-chat-attachment-icon': true,
                    'icon-file': !attachment.isScreenshot,
                    'icon-screenshot': attachment.isScreenshot,
                  })}/>
                  <span className="elixirchat-chat-attachment-filename">{attachment.name}</span>
                  <i className="elixirchat-chat-attachment-remove icon-close-thick"
                    tabIndex={0}
                    onClick={() => this.removeAttachment(attachment.id)}>
                  </i>
                </li>
              ))}
            </ul>
          )}

        </div>

        {isDraggingAttachments && (
          <Fragment>
            <div className="elixirchat-chat-draggable-backdrop"/>
            <div className="elixirchat-chat-draggable-area">
              <i className="elixirchat-chat-draggable-area__icon icon-file"/>
              <div><FormattedMessage id="drop_files" /></div>
            </div>
          </Fragment>
        )}

      </Fragment>
    );
  }
}

export const ChatTextarea = injectIntl(ChatTextareaComponent);
