// widget/VueWidget/IFrameWrapper.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, useAttrs } from 'vue';
import type { ElixirChatWidget } from '../ElixirChatWidget';

const props = defineProps<{
  elixirChatWidget: ElixirChatWidget;
}>();

const iframeRef = ref<HTMLIFrameElement | null>(null);
const iframeContentContainer = ref<HTMLElement | null>(null);
const attrs = useAttrs();

const onIframeReady = (iframeElement: HTMLIFrameElement): Promise<Document> => {
  return new Promise((resolve) => {
    let iframeDocument = iframeElement.contentWindow?.document;

    if (iframeDocument && iframeDocument.readyState === 'complete') {
      resolve(iframeDocument);
    } else {
      iframeElement.addEventListener('load', (e: Event) => {
        const target = e.target as HTMLIFrameElement;
        iframeDocument = target.contentWindow?.document || document;
        resolve(iframeDocument);
      }, { once: true });
    }
  });
};

onMounted(async () => {
  if (!iframeRef.value) return;

  const iframeDocument = await onIframeReady(iframeRef.value);

  const container = iframeDocument.createElement('main');
  container.className = 'elixirchat-widget-main-vue';
  iframeDocument.body.appendChild(container);
  iframeContentContainer.value = container;

  props.elixirChatWidget.setIFrameDocument(iframeDocument);
});

onBeforeUnmount(() => {
  if (iframeContentContainer.value?.parentNode) {
    iframeContentContainer.value.parentNode.removeChild(iframeContentContainer.value);
  }
  iframeContentContainer.value = null;
});
</script>

<template>
  <iframe
    id="elixirchat-widget-iframe"
    :class="attrs.class"
    ref="iframeRef"
  />
  <Teleport
    v-if="iframeContentContainer"
    :to="iframeContentContainer"
  >
    <slot />
  </Teleport>
</template>

// widget/DefaultWidget/IFrameWrapper.tsx
import React, { Component } from 'react';
import { createPortal } from 'react-dom';
import { ElixirChatWidget } from '../ElixirChatWidget';
import { WIDGET_IFRAME_READY } from '../ElixirChatWidgetEventTypes';

export interface IIFrameWrapperProps {
  elixirChatWidget: ElixirChatWidget;
}

export interface IIFrameWrapperState {
  isIframeReady: boolean;
}

export class IFrameWrapper extends Component<IIFrameWrapperProps, IIFrameWrapperState> {

  iframeContentContainer = null;
  iframe = React.createRef();

  state = {
    isIframeReady: false,
  };

  componentDidMount(){
    const { elixirChatWidget } = this.props;

    this.onIframeReady().then(iframeDocument => {
      this.iframeContentContainer = iframeDocument.createElement('main');
      this.iframeContentContainer.className = 'elixirchat-widget-main';
      iframeDocument.body.appendChild(this.iframeContentContainer);

      this.setState({ isIframeReady: true }, () => {
        elixirChatWidget.setIFrameDocument(iframeDocument);
      });
    });
  }

  onIframeReady = () => {
    return new Promise((resolve) => {
      let iframeElement: HTMLIFrameElement = this.iframe.current;
      let iframeDocument = iframeElement.contentWindow.document;

      if (iframeDocument.readyState === 'complete') {
        resolve(iframeDocument);
      }
      else {
        iframeElement.addEventListener('load', (e) => {
          iframeElement = e.target;
          iframeDocument = iframeElement.contentWindow.document;
          resolve(iframeDocument);
        });
      }
    });
  };

  render() {
    const { children, className } = this.props;
    const { isIframeReady } = this.state;

    return (
      <iframe  id='elixirchat-widget-iframe' className={className} ref={this.iframe}>
        {isIframeReady && createPortal(React.Children.only(children), this.iframeContentContainer)}
      </iframe>
    )
  }
}
