// widget/DefaultWidget/IFrameWrapper.vue
<script setup lang="ts">
import { ref, watch, useAttrs, onBeforeUnmount, useTemplateRef } from 'vue';
import { useElixirChatWidget } from './composables/useElixirChatWidget';

const elixirChatWidget = useElixirChatWidget();
const iframeRef = useTemplateRef<HTMLIFrameElement>('iframeRef');
const iframeContentContainer = ref<HTMLElement | null>(null);
const attrs = useAttrs();

const setupIframeContainer = (iframe: HTMLIFrameElement) => {
  const doc = iframe.contentDocument || iframe.contentWindow?.document;
  if (!doc) {
    return;
  }

  const container = doc.createElement('main');
  container.className = 'elixirchat-widget-main-vue';
  doc.body.appendChild(container);
  iframeContentContainer.value = container;

  elixirChatWidget.setIFrameDocument(doc);
};

watch(
  () => iframeRef.value,
  (iframe) => {
    if (!iframe) {
      return;
    }

    if (iframe.contentDocument?.readyState === 'complete') {
      setupIframeContainer(iframe);
    } else {
      iframe.addEventListener('load', () => setupIframeContainer(iframe), { once: true });
    }
  },
  { immediate: true }
);

onBeforeUnmount(() => {
  iframeContentContainer.value = null;
});
</script>

<template>
  <iframe
    id="elixirchat-widget-iframe"
    ref="iframeRef"
    :class="attrs.class"
  />
  <Teleport
    v-if="iframeContentContainer"
    :to="iframeContentContainer"
  >
    <slot />
  </Teleport>
</template>

// widget/DefaultWidget/IFrameWrapper.tsx
import React, { Component } from 'react';
import { createPortal } from 'react-dom';
import { ElixirChatWidget } from '../ElixirChatWidget';
import { WIDGET_IFRAME_READY } from '../ElixirChatWidgetEventTypes';

export interface IIFrameWrapperProps {
  elixirChatWidget: ElixirChatWidget;
}

export interface IIFrameWrapperState {
  isIframeReady: boolean;
}

export class IFrameWrapper extends Component<IIFrameWrapperProps, IIFrameWrapperState> {

  iframeContentContainer = null;
  iframe = React.createRef();

  state = {
    isIframeReady: false,
  };

  componentDidMount(){
    const { elixirChatWidget } = this.props;

    this.onIframeReady().then(iframeDocument => {
      this.iframeContentContainer = iframeDocument.createElement('main');
      this.iframeContentContainer.className = 'elixirchat-widget-main';
      iframeDocument.body.appendChild(this.iframeContentContainer);

      this.setState({ isIframeReady: true }, () => {
        elixirChatWidget.setIFrameDocument(iframeDocument);
      });
    });
  }

  onIframeReady = () => {
    return new Promise((resolve) => {
      let iframeElement: HTMLIFrameElement = this.iframe.current;
      let iframeDocument = iframeElement.contentWindow.document;

      if (iframeDocument.readyState === 'complete') {
        resolve(iframeDocument);
      }
      else {
        iframeElement.addEventListener('load', (e) => {
          iframeElement = e.target;
          iframeDocument = iframeElement.contentWindow.document;
          resolve(iframeDocument);
        });
      }
    });
  };

  render() {
    const { children, className } = this.props;
    const { isIframeReady } = this.state;

    return (
      <iframe  id='elixirchat-widget-iframe' className={className} ref={this.iframe}>
        {isIframeReady && createPortal(React.Children.only(children), this.iframeContentContainer)}
      </iframe>
    )
  }
}
