// widget/VueWidget/components/chatMessages/RatingButton.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import Tooltip from '../tooltip/tooltip.vue';

const { type, messageId, rating = null, isLocked = false } = defineProps<{
  type: 'POSITIVE' | 'NEGATIVE';
  messageId: string;
  rating?: 'POSITIVE' | 'NEGATIVE' | null;
  isLocked?: boolean;
}>();

const emit = defineEmits<{
  rate: [messageId: string, rating: 'POSITIVE' | 'NEGATIVE'];
}>();

const { t } = useI18n();

const optimisticRating = ref<'POSITIVE' | 'NEGATIVE' | null>(null);
const shouldAnimate = ref(false);

const isPositive = computed(() => type === 'POSITIVE');
const isRated = computed(() => Boolean(rating));
const effectiveRating = computed(() => rating ?? optimisticRating.value);
const isActive = computed(() => effectiveRating.value === type);

watch(
  () => [isActive.value, optimisticRating.value, isRated.value],
  ([active, optimistic, rated]) => {
    if (active && optimistic === type && !rated && isPositive.value) {
      shouldAnimate.value = true;
    }
    if (optimistic && rated) {
      optimisticRating.value = null;
    }
  }
);

watch(
  () => isLocked,
  (locked, prevLocked) => {
    if (optimisticRating.value && prevLocked && !locked) {
      optimisticRating.value = null;
    }
  }
);

watch(shouldAnimate, (value) => {
  if (!value) {
    return;
  }

  const timer = setTimeout(() => {
    shouldAnimate.value = false;
  }, 500);

  return () => clearTimeout(timer);
});

const className = computed(() => ({
  'elixirchat-chat-messages__rating-button': true,
  [`elixirchat-chat-messages__rating-button--${isPositive.value ? 'positive' : 'negative'}`]: true,
  'elixirchat-chat-messages__rating-button--rated': isRated.value || isLocked
}));

const iconClassName = computed(() => {
  const icon = isPositive.value
    ? (isActive.value ? 'icon-like-active' : 'icon-like')
    : (isActive.value ? 'icon-dislike-active' : 'icon-dislike');

  return {
    [icon]: true,
    'elixirchat-chat-messages__rating-button--animate': shouldAnimate.value && isActive.value && isPositive.value
  };
});

const tooltipTitle = computed(() => (isRated.value || isLocked) ? t('rate_message_already_rated') : '');

function handleClick(e: Event) {
  if (isRated.value || isLocked) {
    e.preventDefault();
    return;
  }

  e.stopPropagation();

  optimisticRating.value = type;
  emit('rate', messageId, type);
}
</script>

<template>
  <tooltip
    :title="tooltipTitle"
    center
    trigger="click"
  >
    <button
      :class="className"
      @click="handleClick"
    >
      <i :class="iconClassName" />
    </button>
  </tooltip>
</template>

// widget/DefaultWidget/RatingButton.tsx
import React, { useEffect, useRef, useState } from 'react';
import { cn } from '../../utilsCommon';
import { Tooltip } from './Tooltip';

interface IRatingButtonProps {
  type: 'POSITIVE' | 'NEGATIVE';
  messageId: string;
  rating?: 'POSITIVE' | 'NEGATIVE' | null;
  isLocked?: boolean;
  onRate: (messageId: string, rating: 'POSITIVE' | 'NEGATIVE') => void;
  intl: {
    formatMessage: (arg: { id: string }) => string;
  };
}

export const RatingButton = ({ type, messageId, rating, isLocked = false, onRate, intl }: IRatingButtonProps) => {
  const isPositive = type === 'POSITIVE';
  const [optimisticRating, setOptimisticRating] = useState<'POSITIVE' | 'NEGATIVE' | null>(null);
  
  const isRated = Boolean(rating);
  const effectiveRating = rating ?? optimisticRating;
  const isActive = effectiveRating === type;
  const prevLockedRef = useRef(isLocked);

  const className = cn({
    'elixirchat-chat-messages__rating-button': true,
    [`elixirchat-chat-messages__rating-button--${isPositive ? 'positive' : 'negative'}`]: true,
    'elixirchat-chat-messages__rating-button--rated': isRated || isLocked
  });

  const icon = isPositive
    ? isActive ? 'icon-like-active' : 'icon-like'
    : isActive ? 'icon-dislike-active' : 'icon-dislike';

  useEffect(() => {
    const prevLocked = prevLockedRef.current;
    prevLockedRef.current = isLocked;

    if (!optimisticRating) {
      return;
    }
    if (isRated) {
      setOptimisticRating(null);
      return;
    }
    if (prevLocked && !isLocked) {
      setOptimisticRating(null);
    }
  }, [isLocked, isRated, optimisticRating]);

  const tooltipTitle = (isRated || isLocked)
    ? intl.formatMessage({ id: 'rate_message_already_rated' })
    : '';

  return (
    <Tooltip title={tooltipTitle} center trigger="click">
      <button
        className={className}
        onClick={(e) => {
          if (isRated || isLocked) {
            e.preventDefault();
            return;
          }
          setOptimisticRating(prev => prev ?? type);
          onRate(messageId, type);
        }}
      >
        <i className={icon}/>
      </button>
    </Tooltip>
  );
};
