// widget/DefaultWidget/ActionsDropdown.tsx
import React, { useState, useRef, useCallback } from 'react';
import { cn } from '../../utilsCommon';

export interface ActionsDropdownProps {
  onAttachFile: () => void;
  onScreenshot: () => void;
  screenshotAvailable: boolean;
  screenshotLabel: string;
  attachFileLabel: string;
}

export function ActionsDropdown({
  onAttachFile,
  onScreenshot,
  screenshotAvailable,
  screenshotLabel,
  attachFileLabel,
}: ActionsDropdownProps) {
  const [open, setOpen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  const handleBlur = useCallback(
    (e: React.FocusEvent<HTMLDivElement>) => {
      const next = e.relatedTarget;

      if (!next || !containerRef.current?.contains(next)) {
        setOpen(false);
      }
    },
    []
  );

  const handleScreenshotClick = useCallback(() => {
    setOpen(false);
    onScreenshot();
  }, [onScreenshot]);

  const handleAttachFileClick = useCallback(() => {
    setOpen(false);
    onAttachFile();
  }, [onAttachFile]);

  return (
    <div
      ref={containerRef}
      className={cn(
        'elixirchat-chat-textarea__actions',
        'elixirchat-chat-textarea__actions-dropdown-wrap'
      )}
      onBlur={handleBlur}
      tabIndex={-1}
    >
      <span
        className={cn('elixirchat-chat-textarea__actions-button', 'elixirchat-chat-textarea__actions-dropdown-trigger', {
          'elixirchat-chat-textarea__actions-dropdown-trigger--open': open,
        })}
      >
        <button
          type="button"
          className="elixirchat-chat-textarea__actions-dropdown-btn"
          onClick={() => setOpen(o => !o)}
        >
          <i className="icon-file" />
        </button>

        {open && (
          <div className="elixirchat-chat-textarea__actions-dropdown-menu">
            <button
              type="button"
              className="elixirchat-chat-textarea__actions-dropdown-item"
              onClick={handleAttachFileClick}
            >
              <i className="icon-download" />
              <span>{attachFileLabel}</span>
            </button>
            {screenshotAvailable && (
              <button
                type="button"
                className="elixirchat-chat-textarea__actions-dropdown-item"
                onClick={handleScreenshotClick}
              >
                <i className="icon-screenshot" />
                <span>{screenshotLabel}</span>
              </button>
            )}
          </div>
        )}
      </span>
    </div>
  );
}

// widget/VueWidget/components/actionsDropdown.vue
<script setup lang="ts">
import { ref, useTemplateRef } from 'vue';
import { useI18n } from 'vue-i18n';

const { screenshotAvailable = true } = defineProps<{
  screenshotAvailable?: boolean;
}>();
const emit = defineEmits<{
  attachFile: [];
  takeScreenshoot: [];
}>();
const container = useTemplateRef<HTMLDivElement>('container');
const open = ref(false);

const { t } = useI18n();

const toggleOpen = () => open.value = !open.value;

function onFocusOut(event: FocusEvent) {
  const next = event.relatedTarget as Node | null;
  if (!next || !container.value?.contains(next)) {
    open.value = false;
  }
}

function handleScreenshotClick() {
  toggleOpen();
  emit('takeScreenshoot');
}

function handleAttachFileClick() {
  toggleOpen();
  emit('attachFile');
}
</script>

<template>
  <div
    ref="container"
    class="elixirchat-chat-textarea__actions elixirchat-chat-textarea__actions-dropdown-wrap"
    tabindex="-1"
    @focusout="onFocusOut"
  >
    <span class="elixirchat-chat-textarea__actions-button elixirchat-chat-textarea__actions-dropdown-trigger">

      <button
        type="button"
        class="elixirchat-chat-textarea__actions-dropdown-btn"
        @click="toggleOpen"
      >
        <i class="icon-file" />
      </button>

      <div
        v-if="open"
        class="elixirchat-chat-textarea__actions-dropdown-menu"
      >
        <button
          type="button"
          class="elixirchat-chat-textarea__actions-dropdown-item"
          @click="handleAttachFileClick"
        >
          <i class="icon-download" />
          <span>{{ t('attach_files') }}</span>
        </button>
        <button
          v-if="screenshotAvailable"
          type="button"
          class="elixirchat-chat-textarea__actions-dropdown-item"
          @click="handleScreenshotClick"
        >
          <i class="icon-screenshot" />
          <span> {{ t('take_a_screenshot') }}</span>
        </button>
      </div>
    </span>
  </div>
</template>
