// widget/DefaultWidget/Avatar.tsx
import React, { useState } from 'react';

interface AvatarProps {
  src?: string;
  className?: string;
}

export const Avatar: React.FC<AvatarProps> = ({ src, className = 'elixirchat-chat-avatar' }) => {
  const [hasError, setHasError] = useState(false);

  const handleError = () => {
    setHasError(true);
  };

  if (src && !hasError) {
    return (
      <img 
        className={className} 
        src={src} 
        onError={handleError}
        alt="Avatar"
      />
    );
  }

  return <div className={`${className} elixirchat-chat-avatar__system`} />;
};

// widget/DefaultWidget/components/avatar.vue
<script setup lang="ts">
import { ref, computed } from 'vue';

const { src = undefined } = defineProps<{
  src?: string;
}>();

const hasError = ref(false);
const showImage = computed(() => !!src && !hasError.value);
</script>

<template>
  <img
    v-if="showImage"
    v-bind="$attrs"
    class="elixirchat-chat-avatar"
    :src="src"
    alt="Avatar"
    @error="hasError = true"
  >
  <div
    v-else
    v-bind="$attrs"
    class="elixirchat-chat-avatar__system elixirchat-chat-avatar"
  />
</template>
