// widget/DefaultWidget/FullScreenPreview.tsx
import React, { Component } from 'react';
import { ElixirChatWidget } from '../ElixirChatWidget';
import { cn } from '../../utilsCommon';
import { fitDimensionsIntoLimits, isWithinElement } from '../../utilsWidget';
import {
  WIDGET_FULLSCREEN_PREVIEW_CLOSE,
  WIDGET_FULLSCREEN_PREVIEW_OPEN,
  WIDGET_IFRAME_READY,
} from '../ElixirChatWidgetEventTypes';

export interface IFullScreenPreviewProps {
  elixirChatWidget: ElixirChatWidget;
}

export interface IFullScreenPreviewState {
  preview: object,
  gallery: Array<object>,
  previewWidth: number,
  previewHeight: number,
  previewTopMargin: number,
  isVisible: boolean;
  isSlideAnimation: boolean;
}

export class FullScreenPreview extends Component<IFullScreenPreviewProps, IFullScreenPreviewState> {

  state = {
    preview: {},
    gallery: [],
    previewWidth: 0,
    previewHeight: 0,
    previewTopMargin: 0,
    isVisible: false,
    isSlideAnimation: false,
  };

  horizontalPaddings: number = 100;
  verticalPaddings: number = 80;

  video = React.createRef();
  inner = React.createRef();
  nav = React.createRef();

  componentDidMount() {
    const { elixirChatWidget } = this.props;

    elixirChatWidget.on(WIDGET_FULLSCREEN_PREVIEW_OPEN, ({ preview, sender, gallery }) => {
      this.setState({ preview, sender, gallery, isVisible: true });
      this.updatePreviewDimensions(preview);
      this.animateSlide();
    });
    elixirChatWidget.on(WIDGET_IFRAME_READY, () => {
      elixirChatWidget.widgetIFrameDocument.body.addEventListener('keyup', this.onKeyNavigation);
    });
    document.body.addEventListener('keyup', this.onKeyNavigation);
  }

  componentWillUnmount() {
    const { elixirChatWidget } = this.props;
    elixirChatWidget.widgetIFrameDocument.body.removeEventListener('keyup', this.onKeyNavigation);
    document.body.removeEventListener('keyup', this.onKeyNavigation);
  }

  updatePreviewDimensions = (preview) => {
    if (preview.previewType === 'image') {
      this.setImageDimensions(preview);
    }
    else if (preview.previewType === 'video') {
      this.setVideoDimensions(preview);
    }
  };

  setImageDimensions = (preview) => {
    const { width, height } = preview;
    const maxPreviewWidth = window.innerWidth - this.horizontalPaddings;
    const [ previewWidth, previewHeight ] = fitDimensionsIntoLimits(width, height, maxPreviewWidth, null);
    const previewTopMargin = this.calculatePreviewTopMargin(previewHeight);
    this.setState({
      isLoading: false,
      previewWidth,
      previewHeight,
      previewTopMargin,
    });
  };

  setVideoDimensions = (preview) => {
    const { width, height } = preview;
    const maxPreviewWidth = window.innerWidth - this.horizontalPaddings;
    const maxPreviewHeight = window.innerHeight - this.verticalPaddings;
    const [ previewWidth, previewHeight ] = fitDimensionsIntoLimits(width, height, maxPreviewWidth, maxPreviewHeight);
    const previewTopMargin = this.calculatePreviewTopMargin(previewHeight);
    this.setState({
      isLoading: false,
      previewWidth,
      previewHeight,
      previewTopMargin,
    }, () => {
      this.video.current.focus();
    });
  };

  calculatePreviewTopMargin = (previewHeight) => {
    const availableVerticalSpace = window.innerHeight - this.verticalPaddings;
    if (availableVerticalSpace < previewHeight) {
      return 0;
    }
    else {
      return (availableVerticalSpace - previewHeight) / 2;
    }
  };

  onKeyNavigation = (e) => {
    const { preview } = this.state;

    if (e.key === 'Escape') {
      this.closePreview();
    }
    else if (e.key === 'ArrowLeft' && preview.previewType !== 'video') {
      this.navigateToFollowingPreview(-1);
    }
    else if (e.key === 'ArrowRight' && preview.previewType !== 'video') {
      this.navigateToFollowingPreview(1);
    }
  };

  navigateToFollowingPreview = (delta) => {
    const { isVisible, preview, gallery } = this.state;

    if (!isVisible) {
      return false;
    }
    const currentPreviewIndex = gallery.map(image => image.id).indexOf(preview.id);
    let nextPreviewIndex = currentPreviewIndex + delta;
    if (nextPreviewIndex < 0) {
      nextPreviewIndex = gallery.length - 1;
    }
    else if (nextPreviewIndex >= gallery.length) {
      nextPreviewIndex = 0;
    }

    const nextPreview = gallery[nextPreviewIndex];
    this.setState({ preview: nextPreview });
    this.updatePreviewDimensions(nextPreview);
    this.animateSlide();
  };

  animateSlide = () => {
    this.setState({ isSlideAnimation: true });
    setTimeout(() => {
      this.setState({ isSlideAnimation: false });
    }, 200);
  };

  closePreview = () => {
    const { elixirChatWidget } = this.props;
    elixirChatWidget.triggerEvent(WIDGET_FULLSCREEN_PREVIEW_CLOSE);
    this.setState({ isVisible: false });
  };

  onContainerClick = (e) => {
    const isWithinInner = isWithinElement(e.target, this.inner.current);
    const isWithinNav = isWithinElement(e.target, this.nav.current);
    if (!isWithinInner && !isWithinNav) {
      this.closePreview();
    }
  };

  render() {
    const {
      preview,
      previewWidth,
      previewHeight,
      previewTopMargin,
      isSlideAnimation,
      isVisible,
    } = this.state;

    return (
      <div className={cn({
        'elixirchat-widget-full-screen-preview': true,
        'elixirchat-widget-full-screen-preview--visible': isVisible,
      })} onClick={this.onContainerClick}>

        <div ref={this.nav}>
          <span
            className="elixirchat-widget-full-screen-preview__nav elixirchat-widget-full-screen-preview__nav--prev"
            onClick={() => this.navigateToFollowingPreview(-1)}>
            <i className="elixirchat-widget-full-screen-preview__nav-icon icon-chevron-down"/>
          </span>
          <span
            className="elixirchat-widget-full-screen-preview__nav elixirchat-widget-full-screen-preview__nav--next"
            onClick={() => this.navigateToFollowingPreview(1)}>
            <i className="elixirchat-widget-full-screen-preview__nav-icon icon-chevron-down"/>
          </span>
        </div>

        <div className="elixirchat-widget-full-screen-preview__inner"
          ref={this.inner}
          style={{ marginTop: previewTopMargin }}>
          {preview.url && preview.previewType === 'image' && (
            <img className={cn({
              'elixirchat-widget-full-screen-preview__img': true,
              'elixirchat-widget-full-screen-preview__img--animated': isSlideAnimation,
            })}
              width={previewWidth}
              height={previewHeight}
              src={preview.url}
              alt={preview.name}
              onClick={this.closePreview}/>
          )}
          {preview.url && preview.previewType === 'video' && (
            <video  className={cn({
              'elixirchat-widget-full-screen-preview__video': true,
              'elixirchat-widget-full-screen-preview__video--animated': isSlideAnimation,
            })}
              ref={this.video}
              controls={true}
              autoPlay={true}
              width={previewWidth}
              height={previewHeight}
              src={preview.url}/>
          )}
        </div>
      </div>
    );
  }
}

// widget/DefaultWidget/components/FullScreenPreview.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, useTemplateRef, computed } from 'vue';
import { onClickOutside } from '@vueuse/core';
import { useElixirChatWidget } from '@defaultWidget/composables/useElixirChatWidget';
import { fitDimensionsIntoLimits } from '@root/utilsWidgetVue';
import {
  WIDGET_FULLSCREEN_PREVIEW_CLOSE,
  WIDGET_FULLSCREEN_PREVIEW_OPEN,
  WIDGET_IFRAME_READY
} from '@widget/ElixirChatWidgetEventTypes';

type Preview = {
  id?: string;
  url?: string;
  name?: string;
  width?: number;
  height?: number;
  previewType?: 'image' | 'video' | string;
};

const elixirChatWidget = useElixirChatWidget();

const HORIZONTAL_PADDING = 100;
const VERTICAL_PADDING = 80;

const preview = ref<Preview>({});
const gallery = ref<Preview[]>([]);
const previewWidth = ref(0);
const previewHeight = ref(0);
const previewTopMargin = ref(0);
const isVisible = ref(false);
const isSlideAnimation = ref(false);

const videoRef = useTemplateRef<HTMLVideoElement>('videoRef');
const innerRef = useTemplateRef<HTMLElement>('innerRef');
const navRef = useTemplateRef<HTMLElement>('navRef');

let slideAnimationTimeout: ReturnType<typeof setTimeout> | null = null;

function calculatePreviewTopMargin(nextPreviewHeight: number) {
  const availableVerticalSpace = window.innerHeight - VERTICAL_PADDING;
  if (availableVerticalSpace < nextPreviewHeight) {
    return 0;
  }
  return (availableVerticalSpace - nextPreviewHeight) / 2;
}

function setImageDimensions(nextPreview: Preview) {
  const width = Number(nextPreview.width || 0);
  const height = Number(nextPreview.height || 0);
  const maxPreviewWidth = window.innerWidth - HORIZONTAL_PADDING;
  const [nextPreviewWidth, nextPreviewHeight] = fitDimensionsIntoLimits(width, height, maxPreviewWidth, null);
  previewWidth.value = nextPreviewWidth;
  previewHeight.value = nextPreviewHeight;
  previewTopMargin.value = calculatePreviewTopMargin(nextPreviewHeight);
}

function setVideoDimensions(nextPreview: Preview) {
  const width = Number(nextPreview.width || 0);
  const height = Number(nextPreview.height || 0);
  const maxPreviewWidth = window.innerWidth - HORIZONTAL_PADDING;
  const maxPreviewHeight = window.innerHeight - VERTICAL_PADDING;
  const [nextPreviewWidth, nextPreviewHeight] = fitDimensionsIntoLimits(width, height, maxPreviewWidth, maxPreviewHeight);
  previewWidth.value = nextPreviewWidth;
  previewHeight.value = nextPreviewHeight;
  previewTopMargin.value = calculatePreviewTopMargin(nextPreviewHeight);
  setTimeout(() => {
    videoRef.value?.focus();
  });
}

function updatePreviewDimensions(nextPreview: Preview) {
  if (nextPreview.previewType === 'image') {
    setImageDimensions(nextPreview);
  } else if (nextPreview.previewType === 'video') {
    setVideoDimensions(nextPreview);
  }
}

function animateSlide() {
  isSlideAnimation.value = true;
  if (slideAnimationTimeout != null) {
    clearTimeout(slideAnimationTimeout);
  }
  slideAnimationTimeout = setTimeout(() => {
    isSlideAnimation.value = false;
    slideAnimationTimeout = null;
  }, 200);
}

function navigateToFollowingPreview(delta: number) {
  if (!isVisible.value) {
    return;
  }
  const currentPreviewId = preview.value.id;
  const currentPreviewIndex = gallery.value.map((item) => item.id).indexOf(currentPreviewId);
  let nextPreviewIndex = currentPreviewIndex + delta;

  if (nextPreviewIndex < 0) {
    nextPreviewIndex = gallery.value.length - 1;
  } else if (nextPreviewIndex >= gallery.value.length) {
    nextPreviewIndex = 0;
  }

  const nextPreview = gallery.value[nextPreviewIndex];
  if (!nextPreview) {
    return;
  }

  preview.value = nextPreview;
  updatePreviewDimensions(nextPreview);
  animateSlide();
}

function closePreview() {
  elixirChatWidget.triggerEvent(WIDGET_FULLSCREEN_PREVIEW_CLOSE);
  isVisible.value = false;
}

function onKeyNavigation(event: KeyboardEvent) {
  const { key } = event;
  const isVideo = preview.value.previewType === 'video';

  if (key === 'Escape') {
    closePreview();
    return;
  }

  if (isVideo) {
    return;
  }

  if (key === 'ArrowLeft') {
    navigateToFollowingPreview(-1);
  }

  if (key === 'ArrowRight') {
    navigateToFollowingPreview(1);
  }
}

function onOpen(payload: {
  preview: Preview;
  gallery: Preview[];
  sender?: any;
}) {
  preview.value = payload.preview || {};
  gallery.value = Array.isArray(payload.gallery) ? payload.gallery : [];
  isVisible.value = true;
  updatePreviewDimensions(preview.value);
  animateSlide();
}

function onIframeReady() {
  elixirChatWidget.widgetIFrameDocument?.body?.addEventListener('keyup', onKeyNavigation);
}

const isImagePreview = computed(() => Boolean(preview.value.url && preview.value.previewType === 'image'));
const isVideoPreview = computed(() => Boolean(preview.value.url && preview.value.previewType === 'video'));

onClickOutside(innerRef, () => {
  if (isVisible.value) {
    closePreview();
  }
}, {
  ignore: [navRef]
});

onMounted(() => {
  elixirChatWidget.on(WIDGET_FULLSCREEN_PREVIEW_OPEN, onOpen);
  elixirChatWidget.on(WIDGET_IFRAME_READY, onIframeReady);
  document.body.addEventListener('keyup', onKeyNavigation);
});

onBeforeUnmount(() => {
  if (slideAnimationTimeout != null) {
    clearTimeout(slideAnimationTimeout);
    slideAnimationTimeout = null;
  }
  elixirChatWidget.off(WIDGET_FULLSCREEN_PREVIEW_OPEN, onOpen);
  elixirChatWidget.off(WIDGET_IFRAME_READY, onIframeReady);
  elixirChatWidget.widgetIFrameDocument?.body?.removeEventListener('keyup', onKeyNavigation);
  document.body.removeEventListener('keyup', onKeyNavigation);
});
</script>

<template>
  <div
    class="elixirchat-widget-full-screen-preview"
    :class="{ 'elixirchat-widget-full-screen-preview--visible': isVisible }"
  >
    <div ref="navRef">
      <span
        class="elixirchat-widget-full-screen-preview__nav elixirchat-widget-full-screen-preview__nav--prev"
        @click="navigateToFollowingPreview(-1)"
      >
        <i class="elixirchat-widget-full-screen-preview__nav-icon icon-chevron-down" />
      </span>
      <span
        class="elixirchat-widget-full-screen-preview__nav elixirchat-widget-full-screen-preview__nav--next"
        @click="navigateToFollowingPreview(1)"
      >
        <i class="elixirchat-widget-full-screen-preview__nav-icon icon-chevron-down" />
      </span>
    </div>

    <div
      ref="innerRef"
      class="elixirchat-widget-full-screen-preview__inner"
      :style="{ marginTop: `${previewTopMargin}px` }"
    >
      <img
        v-if="isImagePreview"
        class="elixirchat-widget-full-screen-preview__img"
        :class="{ 'elixirchat-widget-full-screen-preview__img--animated': isSlideAnimation }"
        :width="previewWidth"
        :height="previewHeight"
        :src="preview.url"
        :alt="preview.name"
        @click="closePreview"
      >
      <video
        v-if="isVideoPreview"
        ref="videoRef"
        class="elixirchat-widget-full-screen-preview__video"
        :class="{ 'elixirchat-widget-full-screen-preview__video--animated': isSlideAnimation }"
        controls
        autoplay
        :width="previewWidth"
        :height="previewHeight"
        :src="preview.url"
      />
    </div>
  </div>
</template>
